import {
  codePreview,
  comparePreview,
  flowPreview,
  listPreview,
  metricPreview,
  stage,
} from './terminology-preview-html'

import type { TerminologyPreviewCatalog } from './terminology-preview-html'

const BACKEND_PREVIEWS: TerminologyPreviewCatalog = {
  'domain': stage('<div class="pv-address"><small>浏览器地址</small><span>https</span><strong>example.com</strong><span>/products</span></div><div class="pv-address-parts"><b>协议</b><strong>域名</strong><b>路径</b></div>'),
  'dns': flowPreview(['example.com', 'DNS 查询', '203.0.113.10'], 1, 2),
  'url': stage('<div class="pv-address"><span>https</span><strong>shop.example.com</strong><b>/products/42</b><small>?color=blue</small></div><div class="pv-address-parts"><span>协议</span><span>主机</span><span>路径</span><span>参数</span></div>'),
  'http': stage('<div class="pv-request"><div><small>REQUEST</small><strong>GET /api/orders</strong><span>Accept: application/json</span></div><span class="pv-arrow">⇄</span><div><small>RESPONSE</small><strong>200 OK</strong><span>{ orders: [...] }</span></div></div>'),
  'cookie': stage('<div class="pv-cookie"><strong>浏览器 Cookie</strong><span>session_id　••••••</span><span>theme　　　 dark</span><small>随同匹配请求发送的小型数据</small></div>'),
  'https': stage('<div class="pv-lock">🔒</div><div class="pv-copy"><strong>加密连接已建立</strong><span>浏览器 ⇄ TLS ⇄ 服务器</span><small>传输中的内容不可被直接读取</small></div>'),
  'cdn': stage('<div class="pv-network"><span class="pv-node pv-node-accent">源站</span><b>→</b><div class="pv-col"><span class="pv-node">北京边缘节点</span><span class="pv-node">新加坡边缘节点</span><span class="pv-node">法兰克福边缘节点</span></div><b>→</b><span class="pv-node pv-node-success">附近用户</span></div>'),
  'port': stage('<div class="pv-server-box"><strong>服务器 203.0.113.10</strong><div class="pv-port-row"><span>80</span><b>网页 HTTP</b></div><div class="pv-port-row"><span>443</span><b>网页 HTTPS</b></div><div class="pv-port-row"><span>5432</span><b>数据库</b></div></div>'),
  'redirect': flowPreview(['/old-page', '301 Redirect', '/new-page'], 1, 2),
  'websocket': stage('<div class="pv-chat-socket"><div><strong>浏览器</strong><span>发送：你好</span><span>收到：在线</span></div><b>⇄ 持久在线 ⇄</b><div><strong>服务器</strong><span>即时接收</span><span>主动推送</span></div></div>'),
  'api': stage('<div class="pv-api"><div class="pv-api-route"><b>GET</b><strong>/products/42</strong></div><div class="pv-api-response"><small>200 JSON</small><span>{</span><span>　"name": "旅行包",</span><span>　"price": 499</span><span>}</span></div></div>'),
  'json': codePreview(['{', '  "name": "林小满",', '  "roles": ["editor", "author"]', '}'], '结构清楚，可被程序读取'),
  'cors': stage('<div class="pv-origin"><strong>app.example</strong><span>浏览器页面</span></div><span class="pv-arrow">请求数据 →</span><div class="pv-origin"><strong>api.example</strong><span class="pv-chip pv-chip-success">允许该来源</span></div>'),
  'validation': stage('<div class="pv-form"><span class="pv-field">邮箱：lin.example.com</span><strong class="pv-error-field">请输入有效邮箱地址</strong><span class="pv-button">修正后提交</span></div>'),
  'browser-storage': stage('<div class="pv-storage"><div><strong>localStorage</strong><span>theme = dark</span><span>draft = ...</span></div><div><strong>sessionStorage</strong><span>wizardStep = 2</span><span>关闭标签后清除</span></div></div>'),
  'database': stage('<div class="pv-database"><div class="pv-db-top">DATABASE</div><div class="pv-table-row"><strong>users</strong><span>id · email · role</span></div><div class="pv-table-row"><strong>orders</strong><span>id · user_id · total</span></div><div class="pv-table-row"><strong>products</strong><span>id · name · stock</span></div></div>'),
  'sql': codePreview(['SELECT name, total', 'FROM orders', 'WHERE status = \'paid\'', 'ORDER BY total DESC;'], '返回已支付订单'),
  'backend': stage('<div class="pv-network"><span class="pv-node">前端界面</span><span class="pv-arrow">API 请求 →</span><div class="pv-server-box"><strong>后端</strong><span>业务规则</span><span>权限检查</span></div><span class="pv-arrow">↔</span><span class="pv-node pv-node-success">数据库</span></div>'),
  'backend-framework': stage('<div class="pv-framework"><strong>后端框架</strong><div class="pv-row"><span class="pv-chip">路由</span><span class="pv-chip">中间件</span><span class="pv-chip">校验</span></div><div class="pv-row"><span class="pv-chip">数据库</span><span class="pv-chip">错误处理</span></div><small>把常用服务器能力组织成约定</small></div>'),
  'route-endpoint': stage('<div class="pv-route-list"><div><b>GET</b><strong>/api/projects</strong><span>列出项目</span></div><div><b>POST</b><strong>/api/projects</strong><span>创建项目</span></div><div><b>DELETE</b><strong>/api/projects/:id</strong><span>删除项目</span></div></div>'),
  'authentication': flowPreview(['输入账号密码', '验证身份', '签发会话'], 1, 2),
  'authorization': stage('<div class="pv-permission"><div><strong>编辑者 林小满</strong><span class="pv-chip pv-chip-success">可以编辑</span><span class="pv-chip">可以评论</span></div><div><strong>访客 周宁</strong><span class="pv-chip pv-chip-warning">只读</span><span class="pv-chip pv-chip-warning">不能删除</span></div></div>'),
}

const DEPLOYMENT_PREVIEWS: TerminologyPreviewCatalog = {
  'cache': stage('<div class="pv-request"><div><small>第一次</small><strong>源站 820ms</strong><span>保存结果到缓存</span></div><span class="pv-arrow">→</span><div class="pv-pane pv-pane-accent"><small>再次访问</small><strong>缓存 34ms</strong><span>直接命中</span></div></div>'),
  'seo': stage('<div class="pv-search-result"><small>example.com › guides</small><strong>AI 产品上线完整指南</strong><span>从需求、测试到发布的实用清单，帮助团队更稳妥地完成上线。</span></div>'),
  'canonical-url': stage('<div class="pv-url-stack"><span>/article?id=42</span><span>/articles/launch-guide</span><span>/m/launch-guide</span></div><span class="pv-arrow">→</span><div class="pv-pane pv-pane-accent"><small>规范地址</small><strong>/guides/launch</strong></div>'),
  'xml-sitemap': codePreview(['/　　　　　　　　 weekly', '/products　　　　　 daily', '/guides　　　　　　 weekly', '/guides/launch　　　 monthly'], '搜索引擎获得站点页面清单'),
  'robots-txt': codePreview(['User-agent: *', 'Allow: /', 'Disallow: /admin', 'Sitemap: /sitemap.xml']),
  'not-found-page': stage('<div class="pv-result"><strong class="pv-big-number">404</strong><b>这条路走不通</b><span>页面可能已移动，试试搜索或返回首页。</span><span class="pv-button">返回首页</span></div>'),
  'env-var': stage('<div class="pv-env"><div><small>开发环境</small><strong>API_URL</strong><span>localhost</span></div><div><small>生产环境</small><strong>API_URL</strong><span>production-api</span></div><small>代码不变，配置随环境切换</small></div>'),
  'deployment': flowPreview(['代码仓库', '构建产物', '线上服务'], 1, 2),
  'web-hosting': stage('<div class="pv-hosting"><strong>托管平台</strong><div class="pv-row"><span class="pv-node">网页文件</span><span class="pv-node">域名证书</span><span class="pv-node">全球分发</span></div><span class="pv-chip pv-chip-success">example.com 已上线</span></div>'),
  'cd': stage('<div class="pv-pipeline"><span class="pv-pipeline-done">✓ 合并</span><b>→</b><span class="pv-pipeline-done">✓ 构建</span><b>→</b><span class="pv-pipeline-active">• 测试</span><b>→</b><span>发布</span></div>'),
  'staging': stage('<div class="pv-environments"><div><small>STAGING</small><strong>v2.4.0-rc</strong><span>团队验收 · 测试数据</span></div><span class="pv-arrow">验证通过 →</span><div><small>PRODUCTION</small><strong>v2.3.2</strong><span>真实用户 · 真实数据</span></div></div>'),
  'serverless': stage('<div class="pv-event-cloud"><span>订单创建</span><b>⚡</b><strong>函数自动启动</strong><span>发送确认邮件</span></div><small class="pv-caption">有请求时运行，无需长期管理服务器</small>'),
  'monitoring': metricPreview([['可用性', '99.98%', '正常'], ['P95 延迟', '182ms', '稳定'], ['错误率', '0.12%', '低于阈值']]),
  'rollback': flowPreview(['v2.4 出现错误', '切回 v2.3', '服务恢复'], 1, 2),
  'feature-flag': stage('<div class="pv-setting"><div class="pv-copy"><strong>新版结算</strong><span>仅内部团队可见</span></div><span class="pv-switch-on">ON</span></div><div class="pv-setting"><div class="pv-copy"><strong>AI 摘要</strong><span>面向全部用户</span></div><span class="pv-switch-off">OFF</span></div>'),
  'canary-release': stage('<div class="pv-release-users"><div><strong>5% 用户</strong><span class="pv-chip pv-chip-success">v2.4 新版</span></div><div><strong>95% 用户</strong><span class="pv-chip">v2.3 稳定版</span></div></div><small class="pv-caption">先观察少量真实流量，再逐步扩大</small>'),
  'blue-green': stage('<div class="pv-environments"><div class="pv-env-blue"><small>BLUE</small><strong>v2.3 · 在线流量</strong><span>稳定运行</span></div><span class="pv-arrow">流量切换 ⇄</span><div class="pv-env-green"><small>GREEN</small><strong>v2.4 · 待命</strong><span>已完成验证</span></div></div>'),
  'server-logs': codePreview(['12:02:04 INFO  request GET /orders', '12:02:04 INFO  response 200 84ms', '12:02:11 WARN  retry payment webhook', '12:02:12 INFO  retry succeeded']),
}

const PRODUCT_PREVIEWS: TerminologyPreviewCatalog = {
  'user-story': stage('<div class="pv-story"><small>作为</small><strong>经常出差的销售</strong><small>我希望</small><strong>离线查看客户资料</strong><small>从而</small><strong>没有网络也能准备拜访</strong></div>'),
  'use-case': stage('<div class="pv-use-case"><span class="pv-avatar">客</span><strong>重置忘记的密码</strong><div><span>1. 请求重置</span><span>2. 验证邮箱</span><span>3. 设置新密码</span></div><small>成功：重新登录</small></div>'),
  'user-flow': flowPreview(['发现商品', '加入购物车', '完成支付'], 1, 2),
  'user-journey': stage('<div class="pv-journey"><div><small>发现</small><strong>😊</strong><span>广告触达</span></div><div><small>比较</small><strong>😐</strong><span>信息过多</span></div><div><small>购买</small><strong>😣</strong><span>流程繁琐</span></div><div><small>复购</small><strong>😊</strong><span>提醒及时</span></div></div>'),
  'prd': stage('<div class="pv-document"><small>PRD · v1.2</small><strong>智能搜索改版</strong><span>01 背景与目标</span><span>02 用户与场景</span><span>03 功能范围</span><span>04 验收指标</span></div>'),
  'mvp': stage('<div class="pv-scope"><strong>首版必须</strong><span class="pv-chip pv-chip-success">创建项目</span><span class="pv-chip pv-chip-success">邀请成员</span><strong>以后再做</strong><span class="pv-chip">高级报表</span><span class="pv-chip">自动化规则</span></div>'),
  'product-backlog': listPreview([['P0', '修复支付失败'], ['P1', '新增订单筛选'], ['P2', '自定义主题'], ['Idea', '团队排行榜']]),
  'product-roadmap': stage('<div class="pv-roadmap"><div><small>Q3</small><strong>基础体验</strong><span>搜索 · 权限</span></div><div><small>Q4</small><strong>团队协作</strong><span>评论 · 审批</span></div><div><small>Q1</small><strong>智能自动化</strong><span>规则 · AI</span></div></div>'),
  'gantt-chart': stage('<div class="pv-gantt"><div><span>需求</span><b data-name="one"></b></div><div><span>设计</span><b data-name="two"></b></div><div><span>开发</span><b data-name="three"></b></div><div><span>测试</span><b data-name="four"></b></div></div>'),
  'wireframe': stage('<div class="pv-wireframe"><div class="pv-wire-nav">LOGO　　导航　导航</div><div class="pv-wire-body"><div class="pv-wire-copy"><b></b><span></span><span></span><small>按钮</small></div><div class="pv-wire-media">图片占位</div></div></div>'),
  'moodboard': stage('<div class="pv-moodboard"><div data-name="photo">自然光</div><div data-name="type">温暖标题</div><div data-name="color">大地色</div><div data-name="material">纸张纹理</div></div>'),
  'ab-test': stage('<div class="pv-ab"><div><small>A · 原版</small><strong>立即购买</strong><span>转化率 4.8%</span></div><div class="pv-ab-winner"><small>B · 新版</small><strong>免费试用 14 天</strong><span>转化率 6.2% ↑</span></div></div>'),
  'conversion-funnel': stage('<div class="pv-funnel"><span>访问 10,000</span><span>注册 3,200</span><span>激活 1,800</span><strong>付费 640</strong></div>'),
  'crud': stage('<div class="pv-crud"><span><b>C</b> 新建项目</span><span><b>R</b> 查看项目</span><span><b>U</b> 修改项目</span><span><b>D</b> 删除项目</span></div>'),
  'field': stage('<div class="pv-record"><small>用户记录 #1024</small><span><b>name</b> 林小满</span><span><b>email</b> lin@example.com</span><span><b>role</b> editor</span></div>'),
  'data-type': stage('<div class="pv-type-table"><span><b>name</b> string</span><span><b>age</b> number</span><span><b>verified</b> boolean</span><span><b>joinedAt</b> date</span></div>'),
  'import-export': stage('<div class="pv-import"><span class="pv-node">客户名单.csv</span><span class="pv-arrow">导入 →</span><div class="pv-table-small"><b>128 条客户</b><span>已进入系统</span></div><span class="pv-arrow">→ 导出</span><span class="pv-node pv-node-success">报告.xlsx</span></div>'),
}

const TOOLING_PREVIEWS: TerminologyPreviewCatalog = {
  'terminal': codePreview(['$ pnpm dev', '▲ Local: localhost:3000', '✓ Ready in 842ms', '$ _']),
  'browser-devtools': stage('<div class="pv-devtools"><div class="pv-browser-page"><strong>按钮</strong><span>页面内容</span></div><div class="pv-inspector"><small>ELEMENTS</small><strong>&lt;button&gt;保存&lt;/button&gt;</strong><span>color: blue;</span><span>padding: 8px 12px;</span></div></div>'),
  'npm': stage('<div class="pv-package"><strong>package.json</strong><span>dependencies</span><b>react　19.1.1</b><b>next　15.5.0</b><span>scripts</span><b>dev　next dev</b></div><span class="pv-arrow">pnpm install →</span><span class="pv-node pv-node-success">依赖就绪</span>'),
  'build': flowPreview(['源代码', '编译 + 打包', '可部署产物'], 1, 2),
  'ci': stage('<div class="pv-pipeline"><span class="pv-pipeline-done">✓ Lint</span><b>→</b><span class="pv-pipeline-done">✓ Test</span><b>→</b><span class="pv-pipeline-active">• Build</span><b>→</b><span>Merge</span></div>'),
  'lint': codePreview(['src/card.tsx', '  18:7  error  unused variable', '  42:1  warn   line too long', '✖ 2 problems'], '修正代码规范问题'),
  'acceptance-criteria': stage('<div class="pv-checklist"><strong>登录功能验收</strong><span>☑ 正确账号可进入</span><span>☑ 错误密码显示原因</span><span>☑ 提交中不可重复点击</span><span>☐ 键盘操作通过</span></div>'),
  'test-case': stage('<div class="pv-test-case"><small>TC-LOGIN-03</small><strong>错误密码不能登录</strong><span>给定：已注册用户</span><span>当：输入错误密码</span><span>则：停留登录页并提示错误</span></div>'),
  'unit-test': stage('<div class="pv-test-scope"><div class="pv-code"><span>calculateTotal()</span></div><span class="pv-arrow">← 隔离测试 →</span><div class="pv-col"><span class="pv-chip pv-chip-success">输入 2×99</span><span class="pv-chip pv-chip-success">输出 198</span></div></div>'),
  'integration-test': stage('<div class="pv-test-scope"><span class="pv-node">订单服务</span><span class="pv-arrow">↔</span><span class="pv-node">支付适配器</span><span class="pv-arrow">↔</span><span class="pv-node">数据库</span><span class="pv-chip pv-chip-success">协作通过</span></div>'),
  'end-to-end-test': flowPreview(['浏览器填写订单', '真实后端支付', '看到成功页面'], 1, 2),
  'smoke-test': stage('<div class="pv-smoke"><strong>发布后 3 分钟快速检查</strong><span>✓ 首页可打开</span><span>✓ 登录可完成</span><span>✓ 核心订单可创建</span><small>先确认系统没有“冒烟”</small></div>'),
  'regression-test': comparePreview('已有 128 项通过', '改动后仍 128 项通过', '旧功能基线', '确认没有被新改动破坏'),
  'test-coverage': metricPreview([['Statements', '92%', '184 / 200'], ['Branches', '78%', '39 / 50'], ['Functions', '88%', '44 / 50']]),
  'test-double': stage('<div class="pv-test-double"><span class="pv-node">被测订单服务</span><span class="pv-arrow">→</span><div class="pv-node pv-node-accent"><strong>支付 Stub</strong><small>固定返回成功</small></div><span class="pv-caption">替代真实外部支付</span></div>'),
  'test-data-fixture': stage('<div class="pv-fixture"><strong>固定测试数据</strong><span>用户：test@example.com</span><span>商品：演示套餐 ¥99</span><span>订单：pending</span><small>每次测试从相同起点开始</small></div>'),
  'flaky-test': stage('<div class="pv-flaky"><span class="pv-chip pv-chip-success">运行 1　通过</span><span class="pv-chip pv-chip-warning">运行 2　失败</span><span class="pv-chip pv-chip-success">运行 3　通过</span><strong>相同代码，结果不稳定</strong></div>'),
  'tech-stack': stage('<div class="pv-stack"><span class="pv-node pv-node-accent">Next.js · 前端</span><span class="pv-node">Node.js · 服务</span><span class="pv-node">PostgreSQL · 数据</span><span class="pv-node pv-node-success">Vercel · 部署</span></div>'),
  'javascript': codePreview(['const total = items.reduce(', '  (sum, item) => sum + item.price,', '  0', ')'], '网页交互与数据逻辑'),
  'typescript': codePreview(['type Order = {', '  id: string', '  total: number', '}', 'const order: Order = ...'], '写代码时检查数据形状'),
  'python': codePreview(['orders = load_orders()', 'paid = [o for o in orders', '        if o.status == "paid"]', 'print(len(paid))'], '通用脚本与数据处理'),
  'react': stage('<div class="pv-component-tree"><strong>&lt;App /&gt;</strong><span>├─ &lt;Header /&gt;</span><span>└─ &lt;ProductList /&gt;</span><span>　 └─ &lt;ProductCard /&gt; × 6</span></div>'),
  'vue': codePreview(['&lt;script setup&gt;', 'const count = ref(0)', '&lt;/script&gt;', '&lt;button&gt;{{ count }}&lt;/button&gt;'], '响应式组件界面'),
  'nextjs': stage('<div class="pv-framework"><strong>Next.js 应用</strong><div class="pv-row"><span class="pv-chip">页面路由</span><span class="pv-chip">服务端渲染</span></div><div class="pv-row"><span class="pv-chip">API 路由</span><span class="pv-chip">图片优化</span></div><small>React 全栈框架</small></div>'),
  'tailwind-css': codePreview(['&lt;button class="', '  px-4 py-2', '  rounded-lg bg-blue-600', '"&gt;保存&lt;/button&gt;'], '用组合类完成样式'),
  'shadcn-ui': stage('<div class="pv-component-kit"><small>可复制的组件源码</small><span class="pv-field">Email</span><span class="pv-button">Continue</span><div class="pv-row"><span class="pv-chip">可访问性</span><span class="pv-chip">可定制</span></div></div>'),
}

const AI_PREVIEWS: TerminologyPreviewCatalog = {
  'ai-application-basics': stage('<div class="pv-ai-app"><span class="pv-node">用户输入</span><span class="pv-arrow">→</span><div class="pv-col"><span class="pv-node pv-node-accent">模型</span><span class="pv-chip">提示词 + 上下文</span></div><span class="pv-arrow">→</span><span class="pv-node pv-node-success">可用功能</span></div>'),
  'ai-hallucination': stage('<div class="pv-answer-check"><div><strong>AI：该政策始于 2018 年</strong><span class="pv-chip pv-chip-warning">无来源依据</span></div><span class="pv-arrow">核查 →</span><div><strong>资料：2021 年发布</strong><span class="pv-chip pv-chip-success">已纠正</span></div></div>'),
  'vibe-coding': stage('<div class="pv-vibe"><div class="pv-bubble"><strong>“做一个可筛选的任务看板”</strong><span>自然语言描述目标</span></div><span class="pv-arrow">↔</span><div class="pv-code"><span>生成代码</span><span>运行预览</span><span>继续调整</span></div></div>'),
  'multimodal-ai': stage('<div class="pv-multimodal"><span class="pv-node">文字</span><span class="pv-node">图片</span><span class="pv-node">音频</span><span class="pv-arrow">→</span><span class="pv-node pv-node-accent">同一个模型理解</span><span class="pv-arrow">→</span><span class="pv-node pv-node-success">综合回答</span></div>'),
  'context-engineering': stage('<div class="pv-context-pack"><strong>送给模型的工作包</strong><span>目标：修复结算错误</span><span>代码：checkout.ts</span><span>数据：失败日志</span><span>约束：不能改变接口</span></div><span class="pv-arrow">→</span><span class="pv-node pv-node-success">准确修改</span>'),
  'token': stage('<div class="pv-tokenized"><span>“AI</span><b>开发</b><span>助手</span><b>很好</b><span>用”</span></div><small class="pv-caption">文本被切成模型处理的词元单元</small>'),
  'context-window': stage('<div class="pv-window-meter"><div class="pv-row"><strong>上下文窗口</strong><span>6,400 / 8,000 tokens</span></div><div class="pv-progress"><span></span></div><div class="pv-row"><span>系统 800</span><span>历史 3,600</span><span>文件 2,000</span></div></div>'),
  'system-prompt': stage('<div class="pv-message-stack"><div class="pv-system-message"><small>SYSTEM · 最高优先级</small><strong>你是客服助手，回答必须引用知识库。</strong></div><div><small>USER</small><span>如何申请退款？</span></div></div>'),
  'conversation-history': stage('<div class="pv-chat-history"><div><small>USER · 第 1 轮</small><span>我在规划上海两日游。</span></div><div><small>ASSISTANT</small><span>偏好自然还是城市？</span></div><div><small>USER · 第 2 轮</small><strong>城市，而且继续按刚才预算。</strong></div></div>'),
  'prompt': stage('<div class="pv-prompt-card"><small>目标</small><strong>总结这份客户访谈</strong><small>格式</small><span>3 个痛点 + 对应原话</span><small>约束</small><span>不要推测未提及内容</span></div>'),
  'stateless-request': stage('<div class="pv-stateless"><div><small>请求 1</small><span>输入 A → 输出 A</span><b>无记忆</b></div><div><small>请求 2</small><span>必须再次提供背景</span><b>重新开始</b></div></div>'),
  'structured-output': stage('<div class="pv-api-response"><small>严格 JSON 输出</small><span>{</span><span>　"priority": "high",</span><span>　"owner": "Lin",</span><span>　"tasks": 3</span><span>}</span></div><span class="pv-chip pv-chip-success">Schema valid</span>'),
  'streaming-response': stage('<div class="pv-stream"><strong>AI 正在回答</strong><span>先显示第一段内容，</span><span>后续词元持续到达▌</span><div class="pv-stream-packets"><b>1</b><b>2</b><b>3</b><b>…</b></div></div>'),
  'ai-agent': stage('<div class="pv-agent"><span class="pv-node">目标：整理竞品</span><span class="pv-arrow">→</span><div class="pv-col"><span class="pv-node pv-node-accent">规划步骤</span><span class="pv-node">调用搜索</span><span class="pv-node">校验结果</span></div><span class="pv-arrow">→</span><span class="pv-node pv-node-success">交付报告</span></div>'),
  'harness-engineering': stage('<div class="pv-harness"><strong>Agent 运行外壳</strong><div class="pv-row"><span class="pv-chip">权限边界</span><span class="pv-chip">工具注册</span></div><div class="pv-row"><span class="pv-chip">任务状态</span><span class="pv-chip">日志追踪</span></div><small>让模型可靠地完成真实工作</small></div>'),
  'human-in-the-loop': flowPreview(['AI 起草退款决定', '人工审核 / 修改', '批准后执行'], 1, 2),
  'model-context-protocol': stage('<div class="pv-mcp"><span class="pv-node pv-node-accent">AI 应用</span><span class="pv-arrow">MCP 标准协议 ⇄</span><div class="pv-col"><span class="pv-node">文件服务</span><span class="pv-node">数据库</span><span class="pv-node">业务工具</span></div></div>'),
  'skill': stage('<div class="pv-skill-card"><strong>生成周报 Skill</strong><span>指令：汇总本周进度</span><span>工具：项目数据 + 文档</span><span>输出：固定周报模板</span><span class="pv-chip pv-chip-success">可复用能力包</span></div>'),
  'sub-agent': stage('<div class="pv-agent-tree"><strong>主智能体 · 统筹报告</strong><span>├─ 调研子智能体</span><span>├─ 数据子智能体</span><span>└─ 审校子智能体</span><small>并行完成独立子任务</small></div>'),
  'tool-calling': stage('<div class="pv-tool-call"><div><small>AI 决定调用</small><strong>get_weather</strong><span>{ city: "上海" }</span></div><span class="pv-arrow">→</span><div><small>工具返回</small><strong>28°C · 多云</strong><span class="pv-chip pv-chip-success">verified</span></div></div>'),
  'react-pattern': stage('<div class="pv-reason-act"><span><small>THOUGHT</small><strong>需要先查库存</strong></span><b>→</b><span><small>ACTION</small><strong>调用库存工具</strong></span><b>→</b><span><small>OBSERVATION</small><strong>还有 12 件</strong></span></div>'),
  'agent-loop': stage('<div class="pv-loop"><span>观察环境</span><b>→</b><span>决定行动</span><b>→</b><span>调用工具</span><b>→</b><span>检查结果</span><strong>↺ 直到完成</strong></div>'),
  'ttft-tps': metricPreview([['首字延迟 TTFT', '0.42s', '越低越快出现'], ['生成速度 TPS', '68/s', '每秒输出词元']]),
  'token-cost': stage('<div class="pv-cost"><div><small>输入</small><strong>12,400 tokens</strong><span>¥0.18</span></div><div><small>输出</small><strong>2,100 tokens</strong><span>¥0.24</span></div><b>本次合计 ¥0.42</b></div>'),
  'rate-limit': stage('<div class="pv-rate"><div class="pv-row"><strong>API 请求额度</strong><span>84 / 100</span></div><div class="pv-progress"><span></span></div><span class="pv-chip pv-chip-warning">剩余 16 次 · 42 秒后重置</span></div>'),
}

const GIT_PREVIEWS: TerminologyPreviewCatalog = {
  'git': stage('<div class="pv-git-graph"><span>● 初始化</span><b>│</b><span>● 首页</span><b>│╲</b><span>● 功能分支</span><b>│╱</b><strong>● 合并发布</strong></div>'),
  'commit': stage('<div class="pv-commit"><span class="pv-git-dot">●</span><div class="pv-copy"><strong>feat: add project search</strong><span>a3f9c12 · 林小满 · 2 分钟前</span><small>3 files changed, +48 −6</small></div></div>'),
  'branch': stage('<div class="pv-branch"><span>main　●──────●</span><span>　　　 ╲</span><strong>feature/search　●──●</strong></div>'),
  'merge': stage('<div class="pv-branch"><span>main　●───────● merge</span><span>　　　 ╲　　╱</span><strong>feature　●──●</strong></div>'),
  'pull': flowPreview(['远程仓库新提交', 'git pull', '本地分支更新'], 1, 2),
  'push': flowPreview(['本地新提交', 'git push', '远程仓库更新'], 1, 2),
  'clone': flowPreview(['远程仓库 URL', 'git clone', '本地完整副本'], 1, 2),
  'pull-request': stage('<div class="pv-pr"><div class="pv-row"><strong>feat/search → main</strong><span class="pv-chip pv-chip-success">Checks passed</span></div><span>新增项目搜索与空状态</span><div class="pv-row"><span>2 approvals</span><span class="pv-button">Merge</span></div></div>'),
  'worktree': stage('<div class="pv-worktrees"><div><strong>main/</strong><span>修复线上问题</span></div><div><strong>feature-search/</strong><span>继续开发搜索</span></div><small>同一仓库，两个独立工作目录</small></div>'),
  'stash': stage('<div class="pv-stash"><div><small>工作区</small><strong>未完成的筛选改动</strong><span>git stash ↓</span></div><div><small>暂存栈 stash@{0}</small><strong>安全保存</strong><span>git stash pop ↑</span></div></div>'),
  'gitignore': codePreview(['# dependencies', 'node_modules/', '# secrets', '.env.local', '# build output', '.next/'], '这些文件不进入版本控制'),
  'diff': stage('<div class="pv-diff"><span class="pv-diff-remove">− const limit = 10</span><span class="pv-diff-add">+ const limit = 20</span><span>　 return fetchItems(limit)</span><small>一眼看出删除与新增</small></div>'),
}

export const TERMINOLOGY_SYSTEM_PREVIEWS: TerminologyPreviewCatalog = {
  ...BACKEND_PREVIEWS,
  ...DEPLOYMENT_PREVIEWS,
  ...PRODUCT_PREVIEWS,
  ...TOOLING_PREVIEWS,
  ...AI_PREVIEWS,
  ...GIT_PREVIEWS,
}
