export const AI_SECURITY_ERROR_CODES = [
  'SECURITY_ASSESSMENT_ACTIVE',
  'SECURITY_ASSESSMENT_INPUT_CHANGED',
  'SECURITY_ASSESSMENT_NOT_FOUND',
  'SECURITY_ASSESSMENT_RETRY_EXHAUSTED',
  'SECURITY_ADAPTER_NOT_READY',
  'SECURITY_ADAPTER_VERSION_CHANGED',
  'SECURITY_COVERAGE_INVALID',
  'SECURITY_INVALID_FINGERPRINT',
  'SECURITY_INVALID_PATH',
  'SECURITY_INVALID_STATE_TRANSITION',
  'SECURITY_LLM_CONFIG_CHANGED',
  'SECURITY_LEASE_LOST',
  'SECURITY_MODE_DISABLED',
  'SECURITY_OVERRIDE_INVALID',
  'SECURITY_PUBLISH_BLOCKED',
  'SECURITY_QUEUE_FULL',
  'SECURITY_REPORT_INVALID',
  'SECURITY_SCHEMA_NOT_READY',
  'SECURITY_SERVICE_DISABLED',
  'SECURITY_SERVICE_STATE_CONFLICT',
  'SECURITY_SOURCE_FETCH_FAILED',
  'SECURITY_SOURCE_INVALID',
  'SECURITY_SOURCE_NOT_ALLOWED',
  'SECURITY_SOURCE_TRANSIENT',
  'SECURITY_WORKER_FAILED',
  'SECURITY_WORKER_SHUTDOWN',
  'SECURITY_WORKER_TIMEOUT',
  'SOURCE_LIMIT_EXCEEDED',
] as const

export type AiSecurityErrorCode = typeof AI_SECURITY_ERROR_CODES[number]

const RETRYABLE_SECURITY_ERROR_CODES = new Set<string>([
  'SECURITY_ADAPTER_NOT_READY',
  'SECURITY_ASSESSMENT_INPUT_CHANGED',
  'SECURITY_SOURCE_FETCH_FAILED',
  'SECURITY_SOURCE_TRANSIENT',
  'SECURITY_WORKER_FAILED',
  'SECURITY_WORKER_SHUTDOWN',
  'SECURITY_WORKER_TIMEOUT',
])

export class AiSecurityError extends Error {
  readonly code: AiSecurityErrorCode

  constructor(code: AiSecurityErrorCode, message: string, options?: ErrorOptions) {
    super(`${code}: ${message}`, options)
    this.code = code
    this.name = 'AiSecurityError'
  }
}

export function isRetryableSecurityErrorCode(code: string) {
  return RETRYABLE_SECURITY_ERROR_CODES.has(code)
}
